CREATE TABLE BOARD (
	BOARD_ID BIGINT AUTO_INCREMENT PRIMARY KEY, -- 게시글 번호
	BOARD_TITLE VARCHAR(20) NOT NULL, -- 제목
	BOARD_CONTENT TEXT NOT NULL, -- 내용
	BOARD_WRITER VARCHAR(10) DEFAULT '익명의 작성자', -- 작성자
	BOARD_COUNT INT DEFAULT 0, -- 조회수
	BOARD_REGIST_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, -- 등록 일자
	BOARD_UPDATE_DATE DATETIME -- 수정 일자
);

DROP TABLE BOARD;

SELECT * FROM BOARD;